<?php

/**
 * @file
 * Primary module file for the Pokedex module.
 */

/**
 * Implements hook_theme().
 */
function poke_fetcher_theme($existing, $type, $theme, $path) {
  return [
    'pokedex_card' => [
      'variables' => [
          'name' => NULL,
          'id' => NULL,
          'image_url' => NULL,
          'types' => [],
          'admin_name' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_views_view().
 */
function poke_fetcher_preprocess_views_view(array &$variables) {
  if ($variables['view']->id() === 'pokedex_roster') {
    $variables['#attached']['library'][] = 'poke_fetcher/list_style';
  }
}